### ISSUE TITLE
Ошибка при попытке удалить Endpoint.

### ISSUE THREAD

**Issue by newohrim** [Team-project-CS/ms#23]
Mock сервер выдает ошибку 500 при попытке удалить endpoint.

Address: http://178.21.11.9:8082/api/endpointId=008e94b0-20f8-4e42-8cf7-1aecd730c1ef
Method: DELETE.

Сообщение об ошибке:
`{"message":"Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'; nested exception is java.lang.IllegalArgumentException: UUID string too large","timestamp":"13-03-2023 11:12:35","path":"/api/endpointId=008e94b0-20f8-4e42-8cf7-1aecd730c1ef"}`

**Comment by Allexandere** [comment]
Путь должен выглядеть следующим образом
"/api/008e94b0-20f8-4e42-8cf7-1aecd730c1ef"
![image](https://user-images.githubusercontent.com/39259989/224689214-227942e5-e89a-4f14-a04b-330c38afd4a3.png)
